version: "3"
services: 
    app:
        # user 0:0 is userid and group ID of root user
        user: 0:0
        build:
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"

# chown -R $(whoami):$(whoami) app/ 
# 
# docker-compose run app sh -c "django-admin.py startproject app ."